name: Wind Alert Monitor

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 2 PM UTC (adjust as needed)
  workflow_dispatch:

jobs:
  check-wind:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Run wind alert script
        run: python wind_alert.py
