name: Wind Alert

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  check_wind_forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager sendgrid
    - name: Run wind alert script
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
      run: python wind_alert.py
